[package]
name = "clone_jira_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clearscreen = "3.0.0"
colored = "2.1.0"
ellipse = "0.2.0"
itertools = "=0.13.0"
serde = {version="1.0.214", features = ["derive"] }
serde_json = "1.0.132"

[dev-dependencies]
tempfile = "3.13.0"
